### ISSUE TITLE
Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by ugogo** [rmosolgo/react-rails-hot-loader#12]
Hey!

Running rails server gives me following error, any suggestion?

```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/eventmachine-1.2.0.1/rubyeventmachine.bundle (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/eventmachine-1.2.0.1/rubyeventmachine.bundle (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by rmosolgo** [comment]
Here's the end of that "Referenced from"

> eventmachine-1.2.0.1/rubyeventmachine.bundle (which was built for Mac OS X 10.12)

Which makes me think it's a missing dependency for EventMachine (this gem uses EventMachine for a websocket server).

Are you on OSX? Here's a [similar bug report](https://github.com/Homebrew/homebrew-core/issues/4902) where a package from homebrew failed with the same error. It's a bit of a hack, but you could try updating your homebrew, then installing the package mentioned there. Maybe that would cause it to install the missing dependency!

**Comment by ugogo** [comment]
Yey, thanks! `[HotLoader] connected` 👍 

However, is there a way to change the default assets folder ?

> does reload JS assets when they change (from /app/assets/javascripts/*.{js,coffee}*)

I tried this

```
# config/initializers/react_rails_hot_loader.rb
React::Rails::HotLoader::AssetChangeSet.asset_glob = "**/*.{js,rb}*" # I <3 Opal
```

but still no reload.

Thanks 🙏

**Comment by rmosolgo** [comment]
You can see here where `app/assets/javascripts` is provided: 

https://github.com/rmosolgo/react-rails-hot-loader/blob/master/lib/hot_loader/asset_change_set.rb#L14

I don't think it's configurable (yet!) but I'm open to a patch if you'd like to improve that :)

**Comment by ugogo** [comment]
Haha ok, thanks for your help 🙌
