### ISSUE TITLE
Adding assets to the watch glob

### ISSUE THREAD

**Issue by willcosgrove** [rmosolgo/react-rails-hot-loader#3]
Currently, it doesn't look like it's possible to modify the glob string used to watch for assets.  I've got a lot of files in my project that are `*.coffee` files, not `*.js.coffee`.  I was able to modify the line

```ruby
asset_glob = path.to_s + "/**/*.js*"
```
to
```ruby
asset_glob = path.to_s + "/**/*.{js,coffee}*"
```
to get me up and running.  I didn't know if you would want to merge in a change like that, or if you would prefer to add some kind of mechanism for configuring the asset glob path.

Either way, I'm up for sending a PR if you're interested in adding it.

Awesome gem by the way!  This is going in all my projects.

**Comment by rmosolgo** [comment]
Yay, happy it works for you too! I think even at PCO I'm the only one who uses it. 

I think it would be great to make it configurable. If it was me, I would:

- remove `asset_glob` from AssetChangeSet altogether. Shouldn't that just be in AssetPath!?
- add a `cattr_accessor` to AssetPath which defaults to your improved glob
- Add a line to the readme about how to override the default 

I suppose a more Rails-y way would be to take `config` in the Railtie but ... Railties wear me out! Your call :P
